version: '3'
services:
  web:
    build: ./
    restart: always
    depends_on:
      - redis
    expose:
      - 80
    environment:
      - LETSENCRYPT_HOST=heckingoodboys.com,www.heckingoodboys.com
      - VIRTUAL_HOST=heckingoodboys.com
      - VIRTUAL_PORT=80
      - REDIS_URL=redis://redis
    env_file:
      - ./.env
    volumes:
      - .:/code

  tasks:
    build: ./
    restart: always
    depends_on:
      - redis
    command: "./scheduled_task.sh"
    environment:
      - REDIS_URL=redis://redis
    env_file:
      - ./.env
    volumes:
      - .:/code

  redis:
    image: redis:6.2.6-alpine
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.10.0-alpine
    container_name: nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.nginx/html/:/usr/share/nginx/html
      - ./.nginx/certs/:/etc/nginx/certs
      - ./.nginx/vhost/:/etc/nginx/vhost.d
    environment:
      - DEFAULT_HOST=heckingoodboys.com
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  acme-companion:
    image: nginxproxy/acme-companion:2.1.2
    container_name: acme-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.nginx/html/:/usr/share/nginx/html
      - ./.nginx/certs/:/etc/nginx/certs
      - ./.nginx/vhost/:/etc/nginx/vhost.d
      - ./.nginx/acme/:/etc/acme.sh
    env_file:
      - ./.env.acme-companion
    depends_on:
      - nginx-proxy
